Added OpenMP course links
arcdocs/arcdocs.github.io pull request #146
Opened 2023-01-27 13:48 UTC by jhodrien

Just added a couple to the guidance section, which at least means it'll pop up if you search for OpenMP.

I'm still on the look out for one with good exercises, so will add that later.

2023-01-27 14:53 UTC, NGRhodes requested changes

2023-01-27 14:53 UTC, NGRhodes commented on book/guidance/recommended_courses.md
> +- [Advanced OpenMP](http://www.archer.ac.uk/training/course-material/2019/06/AdvOpenMP-manch/L01-OpenMPBasics.pdf) from EPCC
Use https://  - the http:// is making my firefox complain.

2023-01-27 14:58 UTC, jhodrien commented on book/guidance/recommended_courses.md
> +- [Advanced OpenMP](http://www.archer.ac.uk/training/course-material/2019/06/AdvOpenMP-manch/L01-OpenMPBasics.pdf) from EPCC
Hmm, but HTTPS has an expired certificate.  Maybe I need to find a better link to this material.

2023-01-27 15:00 UTC, jhodrien commented on book/guidance/recommended_courses.md
> +- [Advanced OpenMP](http://www.archer.ac.uk/training/course-material/2019/06/AdvOpenMP-manch/L01-OpenMPBasics.pdf) from EPCC
https://www.archer2.ac.uk/training/courses/211005-advanced-openmp/

This appears to be the replacement course.  I'll review, and update the link to that if I like it.

2023-01-27 16:31 UTC, jhodrien commented on book/guidance/recommended_courses.md
> +- [Advanced OpenMP](http://www.archer.ac.uk/training/course-material/2019/06/AdvOpenMP-manch/L01-OpenMPBasics.pdf) from EPCC
Fixed in 012c6d5

2023-01-30 11:29 UTC, NGRhodes approved these changes

2023-01-30 11:46 UTC, merged