Gurobi doc
arcdocs/arcdocs.github.io pull request #33
Opened 2021-01-06 15:54 UTC by Sparrow0hawk

adding in documentation for the Gurobi module and instructions for using with R, Python and MATLAB

2021-01-06 17:17 UTC, jhodrien requested changes
Needs a _toc.yml entry.

2021-01-06 17:17 UTC, jhodrien commented on book/software/gurobi.md
> +```note
Throws a build warning.  Used {note} elsewhere?

2021-01-06 17:17 UTC, jhodrien commented on book/software/gurobi.md
> +```note
Throws a build warning.  Used {note} elsewhere?

2021-01-07 17:25 UTC, Sparrow0hawk commented
@jhodrien should have solved these in latest push

2021-01-07 17:26 UTC, jhodrien approved these changes

2021-01-07 17:46 UTC, merged