fixes 36
arcdocs/arcdocs.github.io pull request #37
Opened 2021-01-11 16:23 UTC by Sparrow0hawk

added page in on using temporary storage on compute nodes

- updated toc
- updated usage start page

2021-01-11 16:25 UTC, Sparrow0hawk commented
Also now updated the link in the gaussian page

2021-01-12 09:35 UTC, jhodrien requested changes
Otherwise approve

2021-01-12 09:35 UTC, jhodrien commented on book/usage/scratch.md
> +    1. which is the default and specifies any type of disk
```suggestion
    1. \* which is the default and specifies any type of disk
```

2021-01-12 09:35 UTC, jhodrien commented on book/usage/scratch.md
> +    Reading a writing will be much quicker to a solid state drive and this option should be used if you have lots of read and write operations.
```suggestion
    Reading and writing will be much quicker to a solid state drive and this option should be used if you have lots of read and write operations.
```

2021-01-12 09:35 UTC, jhodrien commented on book/usage/scratch.md
> +  - 1
```suggestion
  - \*
```

2021-01-12 10:27 UTC, merged