Adding software/libraries section
arcdocs/arcdocs.github.io pull request #97
Opened 2021-12-17 16:36 UTC by Sparrow0hawk

This PR aims to add pages for library modules available on ARC3 and ARC4.

Summary of changes:
- library pages in software/libraries
- updated _toc for library pages
- a libraries start page with inline links
- a new templating section for misc scripts for generating pages using jinja2
- a libraries.csv source file used to generate pages (and scripts to reproduce)

2021-12-17 16:36 UTC, Sparrow0hawk commented
One for after the holidays! 🎄

2022-01-14 14:55 UTC, NGRhodes requested changes
Also note encoding issue is causing sphinx to not output ® symbols

2022-01-14 14:55 UTC, NGRhodes commented on book/software/libraries/eigen.md
> +
Missing description, how about (from their website):

"Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms."

2022-01-14 14:55 UTC, NGRhodes commented on book/software/libraries/python-libs.md
> +Read more about python-libs on their [website](https://arcdocs.leeds.ac.uk/software/libraries/python-libs).
Broken URL

2022-01-21 11:28 UTC, Sparrow0hawk commented on book/software/libraries/eigen.md
> +
Updated in f31c285

2022-01-21 11:28 UTC, Sparrow0hawk commented on book/software/libraries/python-libs.md
> +Read more about python-libs on their [website](https://arcdocs.leeds.ac.uk/software/libraries/python-libs).
Resolved with new template logic 7783280

2022-01-21 12:01 UTC, lukeconibear commented on book/software/libraries/armadillo.md
> +The armadillo module is available on ARC3 and ARC4:
```suggestion
The armadillo module is available on ARC4:
```

2022-01-21 12:03 UTC, lukeconibear commented on book/software/libraries/atlas.md
> +The atlas module is available on ARC3 and ARC4:
```suggestion
The atlas module is available on ARC3:
```

2022-01-21 12:08 UTC, lukeconibear commented on book/software/libraries/boost.md
> +  - `module add boost/1.60.0`
```suggestion
* - ARC4
  - boost 1.67.0
  - `module add boost/1.67.0`

* - ARC3
  - boost 1.67.0
  - `module add boost/1.67.0`

* - ARC3
  - boost 1.65.1
  - `module add boost/1.65.1`

* - ARC3
  - boost 1.63.0
  - `module add boost/1.63.0`

* - ARC3
  - boost 1.60.0
  - `module add boost/1.60.0`
```

2022-01-21 12:09 UTC, lukeconibear commented on book/software/libraries/boost.md
> +  - `module add boost/1.60.0`
It would be nice to have the versions in order, with the latest first.

2022-01-21 12:10 UTC, lukeconibear commented on book/software/libraries/atlas.md
> +# Atlas
```suggestion
# ATLAS
```

2022-01-21 12:10 UTC, lukeconibear commented on book/software/libraries/cgal.md
> +# Cgal
```suggestion
# CGAL
```

2022-01-21 12:12 UTC, lukeconibear commented on book/software/libraries/cgal.md
> +The CGAL module is available on ARC3 and ARC4:
```suggestion
The CGAL module is available on ARC4:
```

2022-01-21 12:12 UTC, lukeconibear commented on book/software/libraries/cgal.md
> +  - `module add cgal/5.1`
```suggestion
* - ARC4
  - CGAL 5.1
  - `module add cgal/5.1`

* - ARC4
  - CGAL 4.12.2
  - `module add cgal/4.12.2`
```

2022-01-21 12:13 UTC, lukeconibear commented on book/software/libraries/cube.md
> +The cube module is available on ARC3 and ARC4:
```suggestion
The cube module is available on ARC3:
```

2022-01-21 12:13 UTC, lukeconibear commented on book/software/libraries/cudnn.md
> +# Cudnn
```suggestion
# cuDNN
```

2022-01-21 12:14 UTC, lukeconibear commented on book/software/libraries/cudnn.md
> +Read more about CUDNN on their [website](https://developer.nvidia.com/cudnn).
```suggestion
Read more about cuDNN on their [website](https://developer.nvidia.com/cudnn).
```

2022-01-21 12:14 UTC, lukeconibear commented on book/software/libraries/cudnn.md
> +The CUDNN license is available to read on the [NVIDIA website](https://docs.nvidia.com/deeplearning/cudnn/sla/index.html)
```suggestion
The cuDNN license is available to read on the [NVIDIA website](https://docs.nvidia.com/deeplearning/cudnn/sla/index.html)
```

2022-01-21 12:14 UTC, lukeconibear commented on book/software/libraries/cudnn.md
> +The CUDNN module is available on ARC3 and ARC4:
```suggestion
The CUDNN module is available on ARC4:
```

2022-01-21 12:15 UTC, lukeconibear commented on book/software/libraries/cudnn.md
> +$ module add CUDNN
```suggestion
$ module add cudnn
```

2022-01-21 12:16 UTC, lukeconibear commented on book/software/libraries/cudnn.md
> +The CUDNN module can be loaded into your environment with the following command:
```suggestion
The cuDNN module can be loaded into your environment with the following command:
```

2022-01-21 12:16 UTC, lukeconibear commented on book/software/libraries/cudnn.md
> +## The CUDNN module on the HPC
```suggestion
## The cuDNN module on the HPC
```

2022-01-21 12:18 UTC, lukeconibear commented on book/software/libraries/darshan.md
> +The darshan module is available on ARC3 and ARC4:
```suggestion
The darshan module is available on ARC3:
```

2022-01-21 12:21 UTC, lukeconibear commented on book/software/libraries/dyninst.md
> +The dyninst module is available on ARC3 and ARC4:
```suggestion
The dyninst module is available on ARC3:
```

2022-01-21 12:21 UTC, lukeconibear commented on book/software/libraries/eigen.md
> +The eigen module is available on ARC3 and ARC4:
```suggestion
The eigen module is available on ARC3:
```

2022-01-21 12:22 UTC, lukeconibear commented on book/software/libraries/extrae.md
> +The extrae module is available on ARC3 and ARC4:
```suggestion
The extrae module is available on ARC3:
```

2022-01-21 12:22 UTC, lukeconibear commented on book/software/libraries/ffmpeg.md
> +# Ffmpeg
```suggestion
# FFmpeg
```

2022-01-21 12:24 UTC, lukeconibear commented on book/software/libraries/cgal.md
> +$ module add CGAL
```suggestion
$ module add cgal
```

2022-01-21 12:24 UTC, lukeconibear commented on book/software/libraries/ffmpeg.md
> +$ module add FFmpeg
```suggestion
$ module add ffmpeg
```

2022-01-21 12:25 UTC, lukeconibear commented on book/software/libraries/ffmpeg.md
> +  - `module add ffmpeg/4.0`
```suggestion
* - ARC4
  - FFmpeg 4.0
  - `module add ffmpeg/4.0`

* - ARC3
  - FFmpeg 4.0
  - `module add ffmpeg/4.0`

* - ARC3
  - FFmpeg 3.4
  - `module add ffmpeg/3.4`

* - ARC3
  - FFmpeg 3.2.1
  - `module add ffmpeg/3.2.1`
```

2022-01-21 12:26 UTC, lukeconibear commented on book/software/libraries/fftw.md
> +# Fftw
```suggestion
# FFTW
```

2022-01-21 12:27 UTC, lukeconibear commented on book/software/libraries/fftw.md
> +$ module add FFTW
```suggestion
$ module add fftw
```

2022-01-21 12:28 UTC, lukeconibear commented on book/software/libraries/fftw.md
> +  - `module add fftw/3.3.8`
```suggestion
* - ARC4
  - FFTW 3.3.8
  - `module add fftw/3.3.8`

* - ARC4
  - FFTW 2.1.5
  - `module add fftw/2.1.5`
```

2022-01-21 12:28 UTC, lukeconibear commented on book/software/libraries/gdal.md
> +# Gdal
```suggestion
# GDAL
```

2022-01-21 12:29 UTC, lukeconibear commented on book/software/libraries/gdal.md
> +$ module add GDAL
```suggestion
$ module add gdal
```

2022-01-21 12:30 UTC, lukeconibear commented on book/software/libraries/geos.md
> +# Geos
```suggestion
# GEOS
```

2022-01-21 12:30 UTC, lukeconibear commented on book/software/libraries/geos.md
> +$ module add GEOS
```suggestion
$ module add geos
```

2022-01-21 12:31 UTC, lukeconibear commented on book/software/libraries/glew.md
> +# Glew
```suggestion
# GLEW
```

2022-01-21 12:32 UTC, lukeconibear commented on book/software/libraries/glew.md
> +## The glew module on the HPC
```suggestion
## The GLEW module on the HPC
```

2022-01-21 12:32 UTC, lukeconibear commented on book/software/libraries/glew.md
> +Licensing arrangements for glew are described on their [GitHub page](https://github.com/nigels-com/glew#copyright-and-licensing).
```suggestion
Licensing arrangements for GLEW are described on their [GitHub page](https://github.com/nigels-com/glew#copyright-and-licensing).
```

2022-01-21 12:32 UTC, lukeconibear commented on book/software/libraries/glew.md
> +Read more about glew on their [website](http://glew.sourceforge.net/).
```suggestion
Read more about GLEW on their [website](http://glew.sourceforge.net/).
```

2022-01-21 12:32 UTC, lukeconibear commented on book/software/libraries/glew.md
> +The glew module is available on ARC3 and ARC4:
```suggestion
The glew module is available on ARC3:
```

2022-01-21 12:33 UTC, lukeconibear commented on book/software/libraries/glfw.md
> +# Glfw
```suggestion
# GLFW
```

2022-01-21 12:33 UTC, lukeconibear commented on book/software/libraries/glfw.md
> +Read more about glfw on their [website](http://www.glfw.org/).
```suggestion
Read more about GLFW on their [website](http://www.glfw.org/).
```

2022-01-21 12:33 UTC, lukeconibear commented on book/software/libraries/glfw.md
> +## The glfw module on the HPC
```suggestion
## The GLFW module on the HPC
```

2022-01-21 12:33 UTC, lukeconibear commented on book/software/libraries/glfw.md
> +The glfw module can be loaded into your environment with the following command:
```suggestion
The GLFW module can be loaded into your environment with the following command:
```

2022-01-21 12:34 UTC, lukeconibear commented on book/software/libraries/glfw.md
> +The glfw module is available on ARC3 and ARC4:
```suggestion
The GLFW module is available on ARC3:
```

2022-01-21 12:34 UTC, lukeconibear commented on book/software/libraries/glpk.md
> +# Glpk
```suggestion
# GLPK
```

2022-01-21 12:35 UTC, lukeconibear commented on book/software/libraries/glpk.md
> +Read more about glpk on their [website](https://www.gnu.org/software/glpk/).
```suggestion
Read more about GLPK on their [website](https://www.gnu.org/software/glpk/).
```

2022-01-21 12:35 UTC, lukeconibear commented on book/software/libraries/glpk.md
> +## The glpk module on the HPC
```suggestion
## The GLPK module on the HPC
```

2022-01-21 12:35 UTC, lukeconibear commented on book/software/libraries/glpk.md
> +The glpk module can be loaded into your environment with the following command:
```suggestion
The GLPK module can be loaded into your environment with the following command:
```

2022-01-21 12:35 UTC, lukeconibear commented on book/software/libraries/glpk.md
> +The glpk module is available on ARC3 and ARC4:
```suggestion
The GLPK module is available on ARC3:
```

2022-01-21 12:36 UTC, lukeconibear commented on book/software/libraries/gsl.md
> +# Gsl
```suggestion
# GSL
```

2022-01-21 12:36 UTC, lukeconibear commented on book/software/libraries/gsl.md
> +Read more about gsl on their [website](http://www.gnu.org/software/gsl/).
```suggestion
Read more about GSL on their [website](http://www.gnu.org/software/gsl/).
```

2022-01-21 12:36 UTC, lukeconibear commented on book/software/libraries/gsl.md
> +## The gsl module on the HPC
```suggestion
## The GSL module on the HPC
```

2022-01-21 12:36 UTC, lukeconibear commented on book/software/libraries/gsl.md
> +The gsl module can be loaded into your environment with the following command:
```suggestion
The GSL module can be loaded into your environment with the following command:
```

2022-01-21 12:37 UTC, lukeconibear commented on book/software/libraries/gsl.md
> +The gsl module is available on ARC3 and ARC4:
```suggestion
The GSL module is available on ARC3:
```

2022-01-21 12:37 UTC, lukeconibear commented on book/software/libraries/gstreamer.md
> +# Gstreamer
```suggestion
# GStreamer
```

2022-01-21 12:37 UTC, lukeconibear commented on book/software/libraries/gstreamer.md
> +Read more about gstreamer on their [website](https://gstreamer.freedesktop.org/).
```suggestion
Read more about GStreamer on their [website](https://gstreamer.freedesktop.org/).
```

2022-01-21 12:38 UTC, lukeconibear commented on book/software/libraries/gstreamer.md
> +## The gstreamer module on the HPC
```suggestion
## The GStreamer module on the HPC
```

2022-01-21 12:38 UTC, lukeconibear commented on book/software/libraries/gstreamer.md
> +The gstreamer module can be loaded into your environment with the following command:
```suggestion
The GStreamer module can be loaded into your environment with the following command:
```

2022-01-21 12:38 UTC, lukeconibear commented on book/software/libraries/gstreamer.md
> +The gstreamer module is available on ARC3 and ARC4:
```suggestion
The GStreamer module is available on ARC3:
```

2022-01-21 12:39 UTC, lukeconibear commented on book/software/libraries/hdf5.md
> +# Hdf5
```suggestion
# HDF5
```

2022-01-21 12:39 UTC, lukeconibear commented on book/software/libraries/hdf5.md
> +$ module add HDF5
```suggestion
$ module add hdf5
```

2022-01-21 12:40 UTC, lukeconibear commented on book/software/libraries/hdf5.md
> +  - `module add hdf5/1.10.5`
```suggestion
* - ARC4
  - HDF5 1.10.5
  - `module add hdf5/1.10.5`

* - ARC4
  - HDF5 1.8.21
  - `module add hdf5/1.8.21`

* - ARC3
  - HDF5 1.8.20
  - `module add hdf5/1.8.20`

* - ARC3
  - HDF5 1.8.17(default)
  - `module add hdf5/1.8.17(default)`
```

2022-01-21 12:41 UTC, lukeconibear commented on book/software/libraries/hpctoolkit.md
> +# Hpctoolkit
```suggestion
# HPCToolkit
```

2022-01-21 12:41 UTC, lukeconibear commented on book/software/libraries/hpctoolkit.md
> +Read more about hpctoolkit on their [website](http://hpctoolkit.org/).
```suggestion
Read more about HPCToolkit on their [website](http://hpctoolkit.org/).
```

2022-01-21 12:42 UTC, lukeconibear commented on book/software/libraries/hpctoolkit.md
> +## The hpctoolkit module on the HPC
```suggestion
## The HPCToolkit module on the HPC
```

2022-01-21 12:42 UTC, lukeconibear commented on book/software/libraries/hpctoolkit.md
> +The hpctoolkit module can be loaded into your environment with the following command:
```suggestion
The HPCToolkit module can be loaded into your environment with the following command:
```

2022-01-21 12:42 UTC, lukeconibear commented on book/software/libraries/hpctoolkit.md
> +The hpctoolkit module is available on ARC3 and ARC4:
```suggestion
The hpctoolkit module is available on ARC3:
```

2022-01-21 12:43 UTC, lukeconibear commented on book/software/libraries/hypre.md
> +# Hypre
```suggestion
# HYPRE
```

2022-01-21 12:43 UTC, lukeconibear commented on book/software/libraries/hypre.md
> +Read more about hypre on their [website](http://www.llnl.gov/CASC/hypre).
```suggestion
Read more about HYPRE on their [website](http://www.llnl.gov/CASC/hypre).
```

2022-01-21 12:44 UTC, lukeconibear commented on book/software/libraries/hypre.md
> +## The hypre module on the HPC
```suggestion
## The HYPRE module on the HPC
```

2022-01-21 12:44 UTC, lukeconibear commented on book/software/libraries/hypre.md
> +The hypre module can be loaded into your environment with the following command:
```suggestion
The HYPRE module can be loaded into your environment with the following command:
```

2022-01-21 12:44 UTC, lukeconibear commented on book/software/libraries/hypre.md
> +The hypre module is available on ARC3 and ARC4:
```suggestion
The hypre module is available on ARC3:
```

2022-01-21 12:44 UTC, lukeconibear commented on book/software/libraries/hypre.md
> +  - `module add hypre/2.14.0`
```suggestion
* - ARC3
  - hypre 2.14.0
  - `module add hypre/2.14.0`

* - ARC3
  - hypre 2.11.2
  - `module add hypre/2.11.2`
```

2022-01-21 12:45 UTC, lukeconibear commented on book/software/libraries/intelmpi.md
> +# Intelmpi
```suggestion
# IntelMPI
```

2022-01-21 12:45 UTC, lukeconibear commented on book/software/libraries/intelmpi.md
> +Read more about intelmpi on their [website](https://www.intel.com/content/www/us/en/developer/tools/oneapi/mpi-library.html).
```suggestion
Read more about IntelMPI on their [website](https://www.intel.com/content/www/us/en/developer/tools/oneapi/mpi-library.html).
```

2022-01-21 12:46 UTC, lukeconibear commented on book/software/libraries/intelmpi.md
> +The intelmpi module can be loaded into your environment with the following command:
```suggestion
## The IntelMPI module on the HPC

The IntelMPI module can be loaded into your environment with the following command:
```

2022-01-21 12:46 UTC, lukeconibear commented on book/software/libraries/intelmpi.md
> +  - `module add intelmpi/2019.4.243`
```suggestion
* - ARC4
  - intelmpi 2019.4.243
  - `module add intelmpi/2019.4.243`

* - ARC3
  - intelmpi 2018.2.199
  - `module add intelmpi/2018.2.199`

* - ARC3
  - intelmpi 2017.1.132(default)
  - `module add intelmpi/2017.1.132(default)`
```

2022-01-21 12:47 UTC, lukeconibear commented on book/software/libraries/itac.md
> +# Itac
```suggestion
# ITAC
```

2022-01-21 12:47 UTC, lukeconibear commented on book/software/libraries/itac.md
> +Read more about itac on their [website](https://www.intel.com/content/www/us/en/develop/documentation/get-started-with-itac/top/get-started-with-itac-for-oneapi-on-linux.html).
```suggestion
Read more about ITAC on their [website](https://www.intel.com/content/www/us/en/develop/documentation/get-started-with-itac/top/get-started-with-itac-for-oneapi-on-linux.html).
```

2022-01-21 12:48 UTC, lukeconibear commented on book/software/libraries/itac.md
> +The itac module is available on ARC3 and ARC4:
```suggestion
Read more about ITAC on their [website](https://www.intel.com/content/www/us/en/develop/documentation/get-started-with-itac/top/get-started-with-itac-for-oneapi-on-linux.html).





## The ITAC module on the HPC

The ITAC module can be loaded into your environment with the following command:

```bash
$ module add itac
```

The ITAC module is available on ARC3:
```

2022-01-21 12:48 UTC, lukeconibear commented on book/software/libraries/itac.md
> +Read more about itac on their [website](https://www.intel.com/content/www/us/en/develop/documentation/get-started-with-itac/top/get-started-with-itac-for-oneapi-on-linux.html).
```suggestion
Read more about ITAC on their [website](https://www.intel.com/content/www/us/en/develop/documentation/get-started-with-itac/top/get-started-with-itac-for-oneapi-on-linux.html).
```

2022-01-21 12:49 UTC, lukeconibear commented on book/software/libraries/itac.md
> +The itac module can be loaded into your environment with the following command:
```suggestion
## The ITAC module on the HPC

The ITAC module can be loaded into your environment with the following command:
```

2022-01-21 12:49 UTC, lukeconibear commented on book/software/libraries/itac.md
> +The itac module is available on ARC3 and ARC4:
```suggestion
The ITAC module is available on ARC3:
```

2022-01-21 18:15 UTC, lukeconibear requested changes
Looks good. My comments are mostly minor visual things.

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/suitesparse.md
> +# Suitesparse
```suggestion
# SuiteSparse
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/suitesparse.md
> +Read more about suitesparse on their [website](https://people.engr.tamu.edu/davis/suitesparse.html).
```suggestion
Read more about SuiteSparse on their [website](https://people.engr.tamu.edu/davis/suitesparse.html).
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/suitesparse.md
> +The suitesparse module can be loaded into your environment with the following command:
```suggestion
## The SuiteSparse module on the HPC

The SuiteSparse module can be loaded into your environment with the following command:
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/suitesparse.md
> +The suitesparse module is available on ARC3 and ARC4:
```suggestion
The SuiteSparse module is available on ARC3:
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/suitesparse.md
> +  - `module add suitesparse/5.2.0`
```suggestion
* - ARC3
  - suitesparse 5.2.0
  - `module add suitesparse/5.2.0`

* - ARC3
  - suitesparse 4.5.4
  - `module add suitesparse/4.5.4`
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/superlu.md
> +# Superlu
```suggestion
# SuperLU
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/superlu.md
> +Read more about superlu on their [website](https://portal.nersc.gov/project/sparse/superlu/).
```suggestion
Read more about SuperLU on their [website](https://portal.nersc.gov/project/sparse/superlu/).
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/superlu.md
> +The superlu module can be loaded into your environment with the following command:
```suggestion
## The SuperLU module on the HPC

The SuperLU module can be loaded into your environment with the following command:
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/superlu.md
> +The superlu module is available on ARC3 and ARC4:
```suggestion
The SuperLU module is available on ARC4:
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/tau.md
> +# Tau
```suggestion
# TAU
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/tau.md
> +Read more about tau on their [website](https://www.cs.uoregon.edu/research/tau/home.php).
```suggestion
Read more about TAU on their [website](https://www.cs.uoregon.edu/research/tau/home.php).
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/tau.md
> +The tau module can be loaded into your environment with the following command:
```suggestion
## The TAU module on the HPC

The TAU module can be loaded into your environment with the following command:
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/tau.md
> +The tau module is available on ARC3 and ARC4:
```suggestion
The TAU module is available on ARC3:
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/udunits.md
> +# Udunits
```suggestion
# UDUNITS
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/udunits.md
> +Read more about udunits on their [website](https://www.unidata.ucar.edu/software/udunits/).
```suggestion
Read more about UDUNITS on their [website](https://www.unidata.ucar.edu/software/udunits/).
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/udunits.md
> +The udunits module can be loaded into your environment with the following command:
```suggestion
## The UDUNITS module on the HPC

The UDUNITS module can be loaded into your environment with the following command:
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/udunits.md
> +The udunits module is available on ARC3 and ARC4:
```suggestion
The UDUNITS module is available on ARC3:
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/valgrind.md
> +Read more about valgrind on their [website](https://valgrind.org/).
```suggestion
Read more about Valgrind on their [website](https://valgrind.org/).
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/valgrind.md
> +The valgrind module can be loaded into your environment with the following command:
```suggestion
## The Valgrind module on the HPC

The Valgrind module can be loaded into your environment with the following command:
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/valgrind.md
> +The valgrind module is available on ARC3 and ARC4:
```suggestion
The Valgrind module is available on ARC3:
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/vtk.md
> +# Vtk
```suggestion
# VTK
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/vtk.md
> +Read more about vtk on their [website](https://vtk.org/).
```suggestion
Read more about VTK on their [website](https://vtk.org/).
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/vtk.md
> +The vtk module can be loaded into your environment with the following command:
```suggestion
## The VTK module on the HPC

The VTK module can be loaded into your environment with the following command:
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/vtk.md
> +The vtk module is available on ARC3 and ARC4:
```suggestion
The VTK module is available on ARC3 and ARC4:
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/zeromq.md
> +# Zeromq
```suggestion
# ZeroMQ
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/zeromq.md
> +Read more about zeromq on their [website](https://zeromq.org/).
```suggestion
Read more about ZeroMQ on their [website](https://zeromq.org/).
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/zeromq.md
> +The zeromq module can be loaded into your environment with the following command:
```suggestion
## The ZeroMQ module on the HPC

The ZeroMQ module can be loaded into your environment with the following command:
```

2022-01-21 18:15 UTC, lukeconibear commented on book/software/libraries/zeromq.md
> +The zeromq module is available on ARC3 and ARC4:
```suggestion
The ZeroMQ module is available on ARC3:
```

2022-02-04 12:44 UTC, NGRhodes approved these changes

2022-02-07 10:10 UTC, merged