Proposed update of logging on section
arcdocs/arcdocs.github.io pull request #98
Opened 2022-01-06 16:58 UTC by Sparrow0hawk

This PR revamps our current logging on documentation under the Getting Started section.

It separates out different aspects of logging on and attempts to provide more inline links to steer the user to their desired walkthrough (based on OS and location).

Changes summary: 
- Moved to a multi-page set up (separating connecting from campus or off campus)
- Added a section specifically about connecting from campus with updated guidance 
- Integrated @jhodrien section on fingerprint details as a separate section
- Separated out the section on X11 forwarding
- Slight adjustments to the wording at various walkthrough steps

2022-01-07 11:29 UTC, lukeconibear commented on book/getting_started/logon/logon-campus.md
> +The first time you SSH to either ARC4 or ARC3 you will be prompted to confirm the fingerprint of the host you're connecting to. You can check the unique fingerprints for ARC3 and ARC4 in the [fingerp
```suggestion
The first time you SSH to either ARC4 or ARC3 you will be prompted to confirm the fingerprint of the host you're connecting to. You can check the unique fingerprints for ARC3 and ARC4 in the [fingerprint details](fingerprint-details) below.
```

2022-01-07 11:29 UTC, lukeconibear commented on book/getting_started/logon/logon-campus.md
> +You should confirm the key fingerprints match from fingerprints shown in the [fingerprint details](#fingerprint-details) section and type `yes` and press Enter to proceed.
```suggestion
You should confirm the key fingerprints match from fingerprints shown in the [fingerprint details](fingerprint-details) section and type `yes` and press Enter to proceed.
```

2022-01-07 11:38 UTC, lukeconibear requested changes
Looks good to me. Very minor typo for internal links to fingerprint-details page.

2022-01-07 12:02 UTC, jhodrien commented on book/getting_started/logon/logon-campus.md
> +The first time you SSH to either ARC4 or ARC3 you will be prompted to confirm the fingerprint of the host you're connecting to. You can check the unique fingerprints for ARC3 and ARC4 in the [fingerp
Drop the word below at the end of that sentence, since it isn't anymore.

2022-01-07 16:11 UTC, lukeconibear approved these changes

2022-01-11 13:32 UTC, NGRhodes requested changes
Generally fine, a few typos.
I THINK all the instructions make sense, I have not tried them all out (just the linux/mac ones).

2022-01-11 13:32 UTC, NGRhodes commented on book/getting_started/logon/logon-off-campus.md
> +| 8. After it accepts your password it will request your password again, this time to log into ARC4 (This may not happen automatically and you may need to double click on session name that appears on
on the right hand User sessions section

left ?

2022-01-14 13:43 UTC, NGRhodes approved these changes

2022-01-14 17:05 UTC, merged